# Generated by Django 6.0.7 on 2026-07-10 08:24

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_alter_transaction_category_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='transaction_type', chained_model_field='type', on_delete=django.db.models.deletion.PROTECT, to='cashflow.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, to='cashflow.subcategory'),
        ),
    ]
