# Generated by Django 6.0.7 on 2026-07-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
